[package]
name = "xz-decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project-lite = "0.2"
thiserror = "1"
tokio = "1"
xz2 = { version = "0.1", features = ["tokio", "static"] }